spring:
  application:
    name: sitree

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  jmx:
    enabled: true


oauth:
  url:
    google: https://www.googleapis.com/oauth2/v3/tokeninfo
    github: https://api.github.com/user