spring:
  config:
    activate:
      on-profile: local

#  h2 로컬 설정
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:sitree'
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


#  mysql 로컬 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/sitree'
    username: root
    password:

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type: TRACE
