spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(o8dCxdj5j3NWZX4YCnAMEfnxleTeyod7xsZNheEWW79rxoTS58naHnp6mj5MvjXGxkiPpaEL+eHgdBQPtpGeGeOPn1Jj64ILtNqn3LbKXFKufLQFRPoqW2nPP+DMKA64)
    username: ENC(wx4wlmAiLrqD9J3YvF/ZLOTsTqp2KFHvP8Q/3i2UIGB7C+PTD5D3+LVLGzvPQuSv)