spring:
  application:
    name: sitree

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  auth:
    signature: ENC(HN0i3jHIHQZvGZ3qvnYlcFBTwnQl+dZGwLm9V7GWTfH4hdSGUSofMytAnb5OAHTW)