spring:
  config:
    activate:
      on-profile: local


  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:sitree'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
