spring:
  config:
    activate:
      on-profile: live

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(o8dCxdj5j3NWZX4YCnAMEfnxleTeyod7xsZNheEWW79rxoTS58naHnp6mj5MvjXGxkiPpaEL+eHgdBQPtpGeGeOPn1Jj64ILtNqn3LbKXFKufLQFRPoqW2nPP+DMKA64)
    username: ENC(BapCeJf22I6LpmOL3YN6SFP3TaJLjQGSZOfOucZJIIbT7vSxpeoAm9UQAf4emXqe)
    password: ENC(WBeYUmCujwmPbNE565weug5eJ03/RGOZircahPb3aanpzPxEz3zXdHW0o3L6vQIC)