spring:
  config:
    activate:
      on-profile: live

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(f/HzYBFilX/dBrvFSyV+XqXkYyXOTweQ9IrbIVfwcz2jpBPHsjHbGVMdnEEmeuDAuOogFuLTCZa/k838RhQfyLkltFKvaJblGq2qZTO9ra7312MTc/B4tXwJQqgYv2sPUEpZQ9ufX9PxuwqdE48wY8fKIEWBzjW7fIelriUHC4kotRGXFLlcPHn92q6UKmY5EJuJ4gl9o1J305azLj1hAg==)
    username: ENC(BapCeJf22I6LpmOL3YN6SFP3TaJLjQGSZOfOucZJIIbT7vSxpeoAm9UQAf4emXqe)
    password: ENC(WBeYUmCujwmPbNE565weug5eJ03/RGOZircahPb3aanpzPxEz3zXdHW0o3L6vQIC)