spring:

  application:
    name: sitree

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    jcache:
      config: classpath:ehcache.xml

  jmx:
    enabled: true

server:
  forward-headers-strategy: native

cloud:
  aws:
    s3:
      bucket: sitree-s3
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ENC(pbJdvDAG+GTwVQMqUqJOTJBTrRHC1nwYBExJMbW3Fs/kDLiQ/Olm967CcCqE245LO6L+mu/OEKB8O0gzdWhCyA==)
      secretKey: ENC(qUTUEPZanX+vBpYEU09vDpHNInfAKpH4BLICoBGr6fuQdt4MnrjD2jnwCDhxaBZBLNV+IemheLp9dBgd5M48hxuPIqlBmUtD5jgLcT9KcbE=)

oauth:
  url:
    google: https://www.googleapis.com/oauth2/v3/tokeninfo
    github: https://api.github.com/user