package com.eod.sitree.project.domain.model.type;

import lombok.NoArgsConstructor;

@NoArgsConstructor
public enum TechStackType {
    AARCH64, ADOBE_ILLUSTRATOR, ADOBE_PHOTOSHOP, ADOBE_PREMIERE_PRO, ADOBE_XD, ADONISJS,
    AFTER_EFFECTS, AKKA, ALGOLIA, ALPINE_JS, ANACONDA, ANDROID_STUDIO, ANDROID, ANGULAR, ANGULARJS,
    ANSIBLE, ANT_DESIGN, APACHE_AIRFLOW, APACHE_CASSANDRA, APACHE_GROOVY, APACHE_HADOOP,
    APACHE_KAFKA, APACHE_MAVEN, APACHE_SPARK, APACHE_SUBVERSION, APACHE_TOMCAT, APACHE, APL,
    APPCELERATOR, APPLE_SAFARI, APPLE, APPWRITE, ARCH_LINUX, ARDUINO, ARGO_CD, ASTRO, ATOM,
    AUTODESK_MAYA, AUTODESK_SHOTGRID, AWK, AWS, AZIOS, AZURE_DEVOPS, AZURE_SQL_DATABASE, AZURE,
    BABEL, BACKBONE_JS, BALLERINA, BAMBOO, BASH, BEHANCE, BITBUCKET, BLENDER, BOOTSTRAP, BOWER,
    BROWSERSTACK, BULMA, BUN, C, C_SHARP, C_PLUSPLUS, CAIRO_GRAPHICS, CAKEPHP, CANVA, CAPACITOR,
    CENTOS, CHROME, CIRCLECI, CLARITY, CLION, CLOJURE, CLOJURESCRIPT, CLOUDFLARE_WORKERS,
    CLOUDFLARE, CMAKE, CODEAC, CODECOV, CODEIGNITER, CODEPEN, COFFEESCRIPT, COMPOSER, CONFLUENCE,
    CONSUL, CONTAO, CORE_JS, COSMOS_BD, COUCHDB, CRYSTAL, CSS3, CUCUMBER, CYPRESS, D3_JS, DART,
    DATAGRIP, DATASPELL, DBEAVER, DEBIAN, DENO, DEVICON, DIGITAL_OCEAN, DISCORD_JS, DJANGO_REST,
    DJANGO, DOCKER, DOCTRINE, DROPWIZARD, DRUPAL, ECLIPSE_CEYLON, ECLIPSE_IDE, ECLIPSE_VERT_X,
    ELASTIC_BEATS, ELASTIC_SEARCH, ELECTRON, ELEVENTY, ELIXIR, ELM, EMBEDDED_C, EMBER_JS, ENVOY,
    ERLANG, ESLINT, EXPRESS, FACEBOOK, FASTAPI, FASTIFY, FAUNA, FEATHERS, FEDORA, FIGMA, FILEZILLA,
    FIREBASE, FIREFOX, FLASK, FLUTTER, FORTRAN, FOUNDATION, FSHARP, GATLING, GATSBY, GAZEBO, GCC,
    GENTOO, GHOST, GIMP, GIT, GITBOOK, GITHUB_ACTIONS, GITHUB_CODESPACES, GITHUB, GITLAB, GITPOD,
    GITTER, GNU_EMACS, GO, GODOT_ENGINE, GOLAND, GOOGLE_CLOUD, GOOGLE, GRADLE, GRAFANA, GRAILS,
    GRAPHQL, GRUNT_JS, GULP_JS, HANDLEBARS, HARDHAT, HARVESTER, HASHICORP_TERRAFORM,
    HASHICORP_VAGRANT, HASHICORP_VAULT, HASKELL, HAXE, HELM, HEROKU, HIBERNATE, HOMEBREW,
    HTML5, HUGO, IBM_SPSS_STATISTICS, IFTTT, INFLUXDB, INKSCAPE_, INSOMNIA, INTELLIJ_IDEA,
    INTERNET_EXPLORER_10_, IONIC, JAEGER_TRACING, JAMSTACK, JASMINE, JAVA, JAVASCRIPT, JEET,
    JEKYLL, JENKINS, JEST, JETBRAINS, JIRA_ALIGN, JIRA, JQUERY, JSON, JULE, JULIA, JUNIT, JUPYTER,
    K3OS, K3S, KAGGLE, KARATE_LABS, KARMA, KERAS, KIBANA, KNEX_JS, KNOCKOUT, KOTLIN, KRAKENJS, KTOR,
    KUBERNETES, LABVIEW, LARAVEL, LATEX, LESS_JS, LINKEDIN, LINUX, LIQUIBASE, LIVEWIRE, LLVM,
    LOGSTASH, LUA, LUMEN, MARKDOWN, MATERIAL_UI, MATERIALIZE, MATLAB, MATPLOTLIB, METEOR_JS,
    MICROSOFT_SQL_SERVER, MINITAB, MOBX, MOCHA, MODX, MOLECULER, MONGODB, MONGOOSE_JS, MOODLE,
    MS_DOS, MYSQL, NANO, NEROG, NEST_JS, NETWORKX, NEW4J, NEXT_JS, NGINX, NHIBERNATE, NIM, NIMBLE,
    NIXOS, NODE_JS, NODEMON, NPM, NUGET, NUMPY, NUXT_JS, NW_JS, OBJECTIVE_C, OCAML, OH_MY_ZSH,
    OKTA, OPENAL, OPENAPI, OPENCL, OPENCV, OPENGL, OPENSTACK, OPENSUSE, OPENTELEMETRY, OPERA,
    ORACLE, P5_JS, PACKER, PANDAS, PERL, PFSENSE, PHALCON, PHOENIX_FRAMEWORK, PHOTON_ENGINE_,
    PHP, PHPSTORM, PLAYWRITE, PLOTY, PODMAN, POLYGON, PORTAINER, POSTCSS, POSTGRESSQL, POSTMAN,
    POWERSHELL, PROCESSING, PROMETHEUS, PROTRACTOR_TEST, PURESCRIPT, PUTTY, PYCHARM, PYSCRIPT,
    PYTEST, PYTHON_POETRY, PYTHON, PYTORCH, QODANA, QT_FRAMEWORK, QUARKUS, QUASAR, QWIK, R,
    RABBITMQ, RANCHER, RASPBERRY_PI, REACH, REACT_BOOTSTRAP, REACT, REALM, RED_HAT, RECT, REDIS,
    REDUX, RIDER, ROBOT_OPERATING_SYSTEM, ROCKSDB, ROLLUP_JS, RSPEC, RSTUDIO, RUBY_ON_RAILS, RUBY,
    RUBYMINE, RUST, SALESFORCE, SANITY, SASS, SCALA, SCALINGO, SELENIUM, SEMA_SOFTWARE, SEQUELIZE,
    SHOPWARE, SIMPLE_DIRECTMEDIA_LAYER, SKETCH, SLACK, SOCKET_IO, SOLID_JS, SOLIDITY, SONARQUBE,
    SOURCETREE, SPLUNK, SPRING, SQL_DEVELOPER, SQLALCHEMY, SQLITE, SSH, STACK_OVERFLOW, STATA,
    STORYBOOK, STREAMLIT, STYLUS, SVELTE, SWAGGER, SWIFT, SYMFONY, TAILWIND_CSS, TAURI, TENSORFLOW,
    TEX, THE_ALGORITHMS, THREE_JS, TITANIUM_SDK, TORTOISEGIT, TOWER, TRAEFIK_MESH, TRAEFIK_PROXY,
    TRAVIS_CI, TRELLO, TWITTER, TYPESCRIPT, TYPO3, UBUNTU, UML, UNITY, UNIX, UNREAL_ENGINE, UWSGI,
    V8, VALA, VERCEL, VEUTIFY, VIM, VISUAL_STUDIO_CODE, VISUAL_STUDIO, VITE_JS, VITE, VSPHERE,
    VUE_JS, VUE_STOREFRONT, VYPER, WEBASSEMBLY, WEBFLOW, WEBLATE, WEBPACK, WEBSTORM, WINDOWS_8,
    WINDOWS_11, WOOCOMMERCE, WORDPRESS, XAMARIN, XCODE, XML, YAML, YARN, YII_FRAMEWORK,
    ZEND_FRAMEWORK, ZIG,
    ;

    private String techStackImageUrl;

    TechStackType(String techStackImageUrl) {
        this.techStackImageUrl = techStackImageUrl;
    }
}
